# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_updated', models.DateField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
