# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
