# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='customer_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
