# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170916_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
