# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170916_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=32),
        ),
    ]
